<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!--
        Define o Spring Boot como "pai" do projeto.
        Ele fornece configurações e versões compatíveis das bibliotecas.
    -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.6</version>
        <relativePath/>
    </parent>

    <!-- Identificação do nosso projeto -->
    <groupId>br.com.smartdispatch</groupId>
    <artifactId>smart-dispatch</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <name>smart-dispatch</name>

    <description>
        Sistema inteligente para gestão e distribuição de chamados técnicos
    </description>

    <!-- Versão do Java utilizada pelo projeto -->
    <properties>
        <java.version>21</java.version>
    </properties>

    <dependencies>

        <!--
            Permite criar uma aplicação web:
            controllers, requisições HTTP, JSON e servidor Tomcat.
        -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Ferramentas para testes automatizados -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <!-- Permite executar e empacotar a aplicação Spring Boot -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

        </plugins>
    </build>

</project>