package br.com.smartdispatch.enums;

public enum TipoEventoChamado {

    CHAMADO_CRIADO,
    DADOS_CHAMADO_ALTERADOS,
    STATUS_ALTERADO,

    ORDEM_SERVICO_CRIADA,
    ORDEM_SERVICO_ALTERADA,

    TECNICO_ATRIBUIDO,
    TECNICO_ALTERADO,
    TECNICO_REMOVIDO,

    UNIDADE_ORDEM_ALTERADA,

    ATENDIMENTO_INICIADO,
    ATENDIMENTO_FINALIZADO,
    ATENDIMENTO_FINALIZADO_AUTOMATICAMENTE
}