-- Baseline: representa exatamente o schema atual do Smart Dispatch antes de
-- qualquer evolução do Sprint de Ordens de Serviço. Gerada a partir da leitura
-- das entidades JPA reais (não da inspeção de um banco existente).
--
-- Não contém: numeroChamadoInterno, contador de chamados, sequence nova de
-- numeroOrdemServico, chamado opcional em OrdemServico, ou qualquer outra
-- evolução planejada para as próximas migrations deste sprint.

CREATE TABLE contratos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cidade VARCHAR(255),
    secretario_responsavel VARCHAR(255),
    sla_horas INTEGER,
    link_portal_chamados VARCHAR(255)
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    perfil VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL,
    telefone VARCHAR(255),
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);

CREATE TABLE bases_operacionais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    endereco VARCHAR(255),
    cep VARCHAR(8),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    contrato_id BIGINT NOT NULL,
    CONSTRAINT fk_bases_operacionais_contrato
        FOREIGN KEY (contrato_id) REFERENCES contratos (id)
);

CREATE TABLE unidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    endereco VARCHAR(255),
    cep VARCHAR(8),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    contrato_id BIGINT NOT NULL,
    CONSTRAINT fk_unidades_contrato
        FOREIGN KEY (contrato_id) REFERENCES contratos (id)
);

CREATE TABLE tecnicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    base_operacional_id BIGINT NOT NULL,
    ativo BOOLEAN NOT NULL,
    CONSTRAINT uk_tecnicos_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_tecnicos_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_tecnicos_base_operacional
        FOREIGN KEY (base_operacional_id) REFERENCES bases_operacionais (id)
);

CREATE TABLE chamados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_chamado VARCHAR(255) NOT NULL,
    link_chamado_osti VARCHAR(1000) NOT NULL,
    unidade_id BIGINT NOT NULL,
    nome VARCHAR(255),
    email VARCHAR(255),
    telefone VARCHAR(255),
    identificacao VARCHAR(255),
    numero_patrimonio VARCHAR(255),
    tipo VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    prioridade VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000) NOT NULL,
    data_abertura TIMESTAMP NOT NULL,
    data_finalizacao TIMESTAMP,
    CONSTRAINT fk_chamados_unidade
        FOREIGN KEY (unidade_id) REFERENCES unidades (id)
);

CREATE TABLE ordens_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_ordem_servico VARCHAR(255) NOT NULL,
    chamado_id BIGINT NOT NULL,
    tecnico_id BIGINT,
    unidade_atendimento_id BIGINT NOT NULL,
    data_atribuicao_tecnico TIMESTAMP,
    data_check_in TIMESTAMP,
    data_check_out TIMESTAMP,
    CONSTRAINT uk_ordens_servico_numero UNIQUE (numero_ordem_servico),
    CONSTRAINT fk_ordens_servico_chamado
        FOREIGN KEY (chamado_id) REFERENCES chamados (id),
    CONSTRAINT fk_ordens_servico_tecnico
        FOREIGN KEY (tecnico_id) REFERENCES tecnicos (id),
    CONSTRAINT fk_ordens_servico_unidade_atendimento
        FOREIGN KEY (unidade_atendimento_id) REFERENCES unidades (id)
);

CREATE TABLE comentarios_chamado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chamado_id BIGINT NOT NULL,
    ordem_servico_id BIGINT,
    autor_id BIGINT NOT NULL,
    texto VARCHAR(2000) NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    CONSTRAINT fk_comentarios_chamado_chamado
        FOREIGN KEY (chamado_id) REFERENCES chamados (id),
    CONSTRAINT fk_comentarios_chamado_ordem_servico
        FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id),
    CONSTRAINT fk_comentarios_chamado_autor
        FOREIGN KEY (autor_id) REFERENCES usuarios (id)
);

CREATE TABLE historicos_chamado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chamado_id BIGINT NOT NULL,
    ordem_servico_id BIGINT,
    tipo_evento VARCHAR(60) NOT NULL,
    descricao VARCHAR(1000) NOT NULL,
    data_evento TIMESTAMP NOT NULL,
    CONSTRAINT fk_historicos_chamado_chamado
        FOREIGN KEY (chamado_id) REFERENCES chamados (id),
    CONSTRAINT fk_historicos_chamado_ordem_servico
        FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id)
);

CREATE INDEX idx_historico_chamado_data
    ON historicos_chamado (chamado_id, data_evento);
